/**
 * Todos los títulos que la fuente ha mandado hasta hoy.
 *
 * Copiados de la base tal cual, para que el test de traducción se mida contra
 * lo que de verdad llega y no contra una docena de ejemplos elegidos por quien
 * escribió las reglas -- que es como se consigue un cien por cien que no
 * significa nada.
 *
 * No hace falta mantenerlo al día: si la fuente añade títulos nuevos y las
 * reglas no los cubren, eso no lo detecta esta lista sino la pantalla, que los
 * enseñará en inglés. Esto sirve para no romper hacia atrás lo que ya se
 * traducía.
 */
export const TITULOS: string[] = [
  "10-Year Note Auction",
  "10-Year TIPS Auction",
  "15-Year Mortgage Rate",
  "17-Week Bill Auction",
  "2-Year FRN Auction",
  "2-Year Note Auction",
  "20-Year Bond Auction",
  "3-Month Bill Auction",
  "3-Year Note Auction",
  "30-Year Bond Auction",
  "30-Year Mortgage Rate",
  "30-Year TIPS Auction",
  "4-Week Bill Auction",
  "5-Year Note Auction",
  "5-Year TIPS Auction",
  "52-Week Bill Auction",
  "6-Month Bill Auction",
  "6-Week Bill Auction",
  "7-Year Note Auction",
  "8-Week Bill Auction",
  "ADP Employment Change",
  "ADP Employment Change Weekly",
  "API Crude Oil Stock Change",
  "Average Hourly Earnings MoM",
  "Average Hourly Earnings YoY",
  "Average Weekly Hours",
  "Baker Hughes Oil Rig Count",
  "Baker Hughes Total Rigs Count",
  "Balance of Trade",
  "Building Permits Final",
  "Building Permits MoM Final",
  "Building Permits MoM Prel",
  "Building Permits Prel",
  "Business Inventories MoM",
  "Capacity Utilization",
  "CB Consumer Confidence",
  "CB Leading Index MoM",
  "Challenger Job Cuts",
  "Chicago Fed National Activity Index",
  "Chicago PMI",
  "Christmas",
  "Columbus Day",
  "Construction Spending MoM",
  "Consumer Credit Change",
  "Consumer Inflation Expectations",
  "Continuing Jobless Claims",
  "Core Inflation Rate MoM",
  "Core Inflation Rate YoY",
  "Core PCE Price Index MoM",
  "Core PCE Price Index YoY",
  "Core PCE Prices QoQ",
  "Core PCE Prices QoQ 2nd Est",
  "Core PCE Prices QoQ Adv",
  "Core PCE Prices QoQ Final",
  "Core PPI MoM",
  "Core PPI YoY",
  "Corporate Profits QoQ",
  "Corporate Profits QoQ Final",
  "Corporate Profits QoQ Prel",
  "CPI",
  "CPI s.a",
  "Current Account",
  "Dallas Fed Manufacturing Index",
  "Dallas Fed Services Index",
  "Dallas Fed Services Revenues Index",
  "Durable Goods Orders ex Defense MoM",
  "Durable Goods Orders Ex Transp MoM",
  "Durable Goods Orders MoM",
  "EIA Crude Oil Imports Change",
  "EIA Crude Oil Stocks Change",
  "EIA Cushing Crude Oil Stocks Change",
  "EIA Distillate Fuel Production Change",
  "EIA Distillate Stocks Change",
  "EIA Gasoline Production Change",
  "EIA Gasoline Stocks Change",
  "EIA Heating Oil Stocks Change",
  "EIA Natural Gas Stocks Change",
  "EIA Refinery Crude Runs Change",
  "EIA Short-Term Energy Outlook",
  "Employment Cost - Benefits QoQ",
  "Employment Cost - Wages QoQ",
  "Employment Cost Index QoQ",
  "Existing Home Sales",
  "Existing Home Sales MoM",
  "Export Prices MoM",
  "Export Prices YoY",
  "Exports",
  "Factory Orders ex Transportation",
  "Factory Orders MoM",
  "Fed Balance Sheet",
  "Fed Bank Stress Test Results",
  "Fed Barkin Speech",
  "Fed Barr Speech",
  "Fed Beige Book",
  "Fed Bostic Speech",
  "Fed Bowman Speech",
  "Fed Chair Nominee Kevin Warsh Confirmation Hearing",
  "Fed Chair Powell Speech",
  "Fed Chair Warsh Speech",
  "Fed Chair Warsh Testimony",
  "Fed Collins Speech",
  "Fed Cook Speech",
  "Fed Daly Speech",
  "Fed Golsbee Speech",
  "Fed Goolsbee Speech",
  "Fed Hammack Speech",
  "Fed Interest Rate Decision",
  "Fed Jefferson Speech",
  "Fed Kashkari Speech",
  "Fed Logan Speech",
  "Fed Miran Speech",
  "Fed Musalem Speech",
  "Fed Paulson Speech",
  "Fed Powell Speech",
  "Fed Press Conference",
  "Fed Schmid Speech",
  "Fed Venable Speech",
  "Fed Waller Speech",
  "Fed Williams Speech",
  "FOMC Economic Projections",
  "FOMC Minutes",
  "Foreign Bond Investment",
  "GDP Growth Rate QoQ",
  "GDP Growth Rate QoQ 2nd Est",
  "GDP Growth Rate QoQ Adv",
  "GDP Growth Rate QoQ Final",
  "GDP Price Index QoQ",
  "GDP Price Index QoQ 2nd Est",
  "GDP Price Index QoQ Adv",
  "GDP Price Index QoQ Final",
  "GDP Sales QoQ",
  "GDP Sales QoQ 2nd Est",
  "GDP Sales QoQ Adv",
  "GDP Sales QoQ Final",
  "Goods Trade Balance",
  "Goods Trade Balance Adv",
  "Government Payrolls",
  "House Price Index",
  "House Price Index MoM",
  "House Price Index YoY",
  "Housing Starts",
  "Housing Starts MoM",
  "Import Prices MoM",
  "Import Prices YoY",
  "Imports",
  "Independence Day",
  "Industrial Production MoM",
  "Industrial Production YoY",
  "Inflation Rate MoM",
  "Inflation Rate YoY",
  "Initial Jobless Claims",
  "Interest Rate Projection - 1st Yr",
  "Interest Rate Projection - 2nd Yr",
  "Interest Rate Projection - 3rd Yr",
  "Interest Rate Projection - Current",
  "Interest Rate Projection - Longer",
  "International Monetary Market (IMM) Date",
  "ISM Manufacturing Employment",
  "ISM Manufacturing New Orders",
  "ISM Manufacturing PMI",
  "ISM Manufacturing Prices",
  "ISM Services Business Activity",
  "ISM Services Employment",
  "ISM Services New Orders",
  "ISM Services PMI",
  "ISM Services Prices",
  "Jackson Hole Symposium",
  "Jobless Claims 4-week Average",
  "JOLTs Job Openings",
  "JOLTs Job Quits",
  "Juneteenth National Independence Day",
  "Kansas Fed Composite Index",
  "Kansas Fed Manufacturing Index",
  "Labor Day",
  "LMI Logistics Managers Index",
  "Loan Officer Survey",
  "Manufacturing Payrolls",
  "Manufacturing Production MoM",
  "Manufacturing Production YoY",
  "Martin Luther King, Jr. Day",
  "MBA 30-Year Mortgage Rate",
  "MBA Mortgage Applications",
  "MBA Mortgage Market Index",
  "MBA Mortgage Refinance Index",
  "MBA Purchase Index",
  "Memorial Day",
  "Michigan 5 Year Inflation Expectations Final",
  "Michigan 5 Year Inflation Expectations Prel",
  "Michigan Consumer Expectations Final",
  "Michigan Consumer Expectations Prel",
  "Michigan Consumer Sentiment Final",
  "Michigan Consumer Sentiment Prel",
  "Michigan Current Conditions Final",
  "Michigan Current Conditions Prel",
  "Michigan Inflation Expectations Final",
  "Michigan Inflation Expectations Prel",
  "Money Supply",
  "Monthly Budget Statement",
  "NAHB Housing Market Index",
  "Net Long-term TIC Flows",
  "New Home Sales",
  "New Home Sales MoM",
  "New Year’s Day",
  "NFIB Business Optimism Index",
  "Non Defense Goods Orders Ex Air",
  "Non Farm Payrolls",
  "Non Farm Payrolls Annual Revision",
  "Non Farm Payrolls Annual Revision Prel",
  "Nonfarm Payrolls Private",
  "Nonfarm Productivity QoQ Final",
  "Nonfarm Productivity QoQ Prel",
  "NOPA Crush Report",
  "NY Empire State Manufacturing Index",
  "NY Fed Bill Purchases 1 to 4 months",
  "NY Fed Bill Purchases 4 to 12 months",
  "NY Fed Services Activity Index",
  "NY Fed Treasury Purchases 1 to 2.5 yrs",
  "NY Fed Treasury Purchases 10 to 22.5 yrs",
  "NY Fed Treasury Purchases 22.5 to 30 yrs",
  "NY Fed Treasury Purchases TIPS 7.5 to 30 yrs",
  "Overall Net Capital Flows",
  "Participation Rate",
  "PCE Price Index MoM",
  "PCE Price Index YoY",
  "PCE Prices QoQ",
  "PCE Prices QoQ 2nd Est",
  "PCE Prices QoQ Adv",
  "PCE Prices QoQ Final",
  "Pending Home Sales MoM",
  "Pending Home Sales YoY",
  "Personal Income MoM",
  "Personal Spending MoM",
  "Philadelphia Fed Manufacturing Index",
  "Philly Fed Business Conditions",
  "Philly Fed CAPEX Index",
  "Philly Fed Employment",
  "Philly Fed New Orders",
  "Philly Fed Prices Paid",
  "PPI",
  "PPI Ex Food, Energy and Trade MoM",
  "PPI Ex Food, Energy and Trade YoY",
  "PPI MoM",
  "PPI YoY",
  "President Trump and President Xi Summit",
  "President Trump State of the Union Speech",
  "Prospective Plantings - Corn",
  "Prospective Plantings - Cotton",
  "Prospective Plantings - Soy",
  "Prospective Plantings - Wheat",
  "Quarterly Grain Stocks - Corn",
  "Quarterly Grain Stocks - Soy",
  "Quarterly Grain Stocks - Wheat",
  "RCM/TIPP Economic Optimism Index",
  "Real Consumer Spending QoQ",
  "Real Consumer Spending QoQ 2nd Est",
  "Real Consumer Spending QoQ Adv",
  "Real Consumer Spending QoQ Final",
  "Real Personal Spending MoM",
  "Redbook YoY",
  "Retail Inventories Ex Autos MoM",
  "Retail Inventories Ex Autos MoM Adv",
  "Retail Sales Control Group MoM",
  "Retail Sales Ex Autos MoM",
  "Retail Sales Ex Gas/Autos MoM",
  "Retail Sales MoM",
  "Retail Sales YoY",
  "Richmond Fed Manufacturing Index",
  "Richmond Fed Manufacturing Shipments Index",
  "Richmond Fed Services Revenues Index",
  "S&P Global Composite PMI Final",
  "S&P Global Composite PMI Flash",
  "S&P Global Manufacturing PMI Final",
  "S&P Global Manufacturing PMI Flash",
  "S&P Global Services PMI Final",
  "S&P Global Services PMI Flash",
  "S&P/Case-Shiller Home Price MoM",
  "S&P/Case-Shiller Home Price YoY",
  "Thanksgiving Day",
  "Total Household Debt",
  "Total Vehicle Sales",
  "Treasury Refunding Announcement",
  "Treasury Refunding Financing Estimates",
  "Treasury Secretary Bessent Speech",
  "U-6 Unemployment Rate",
  "UN General Assembly",
  "Unemployment Rate",
  "Unit Labour Costs QoQ Final",
  "Unit Labour Costs QoQ Prel",
  "US President Trump Speech",
  "Used Car Prices MoM",
  "Used Car Prices YoY",
  "Veterans Day",
  "WASDE Report",
  "Washington’s Birthday",
  "Wholesale Inventories MoM",
  "Wholesale Inventories MoM Adv"
];
